version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - '${POSTGRES_DB_PORT:-5432}:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - '${REDIS_PORT:-6379}:6379'
    restart: unless-stopped
    volumes:
      - ./redis:/data
